<?php

use Illuminate\Database\Seeder;

class ProvincesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        $provinces = array(
            array('01','01', 'Chachapoyas'),
            array('01','02', 'Bagua'),
            array('01','03', 'Bongará'),
            array('01','04', 'Condorcanqui'),
            array('01','05', 'Luya'),
            array('01','06', 'Rodríguez de Mendoza'),
            array('01','07', 'Utcubamba'),
            array('02','01', 'Huaraz'),
            array('02','02', 'Aija'),
            array('02','03', 'Antonio Raymondi'),
            array('02','04', 'Asunción'),
            array('02','05', 'Bolognesi'),
            array('02','06', 'Carhuaz'),
            array('02','07', 'Carlos Fermín Fitzcarrald'),
            array('02','08', 'Casma'),
            array('02','09', 'Corongo'),
            array('02','10', 'Huari'),
            array('02','11', 'Huarmey'),
            array('02','12', 'Huaylas'),
            array('02','13', 'Mariscal Luzuriaga'),
            array('02','14', 'Ocros'),
            array('02','15', 'Pallasca'),
            array('02','16', 'Pomabamba'),
            array('02','17', 'Recuay'),
            array('02','18', 'Santa'),
            array('02','19', 'Sihuas'),
            array('02','20', 'Yungay'),
            array('03','01', 'Abancay'),
            array('03','02', 'Andahuaylas'),
            array('03','03', 'Antabamba'),
            array('03','04', 'Aymaraes'),
            array('03','05', 'Cotabambas'),
            array('03','06', 'Chincheros'),
            array('03','07', 'Grau'),
            array('04','01', 'Arequipa'),
            array('04','02', 'Camaná'),
            array('04','03', 'Caravelí'),
            array('04','04', 'Castilla'),
            array('04','05', 'Caylloma'),
            array('04','06', 'Condesuyos'),
            array('04','07', 'Islay'),
            array('04','08', 'La Uniòn'),
            array('05','01', 'Huamanga'),
            array('05','02', 'Cangallo'),
            array('05','03', 'Huanca Sancos'),
            array('05','04', 'Huanta'),
            array('05','05', 'La Mar'),
            array('05','06', 'Lucanas'),
            array('05','07', 'Parinacochas'),
            array('05','08', 'Pàucar del Sara Sara'),
            array('05','09', 'Sucre'),
            array('05','10', 'Víctor Fajardo'),
            array('05','11', 'Vilcas Huamán'),
            array('06','01', 'Cajamarca'),
            array('06','02', 'Cajabamba'),
            array('06','03', 'Celendín'),
            array('06','04', 'Chota'),
            array('06','05', 'Contumazá'),
            array('06','06', 'Cutervo'),
            array('06','07', 'Hualgayoc'),
            array('06','08', 'Jaén'),
            array('06','09', 'San Ignacio'),
            array('06','10', 'San Marcos'),
            array('06','11', 'San Miguel'),
            array('06','12', 'San Pablo'),
            array('06','13', 'Santa Cruz'),
            array('07','01', 'Prov. Const. del Callao'),
            array('08','01', 'Cusco'),
            array('08','02', 'Acomayo'),
            array('08','03', 'Anta'),
            array('08','04', 'Calca'),
            array('08','05', 'Canas'),
            array('08','06', 'Canchis'),
            array('08','07', 'Chumbivilcas'),
            array('08','08', 'Espinar'),
            array('08','09', 'La Convención'),
            array('08','10', 'Paruro'),
            array('08','11', 'Paucartambo'),
            array('08','12', 'Quispicanchi'),
            array('08','13', 'Urubamba'),
            array('09','01', 'Huancavelica'),
            array('09','02', 'Acobamba'),
            array('09','03', 'Angaraes'),
            array('09','04', 'Castrovirreyna'),
            array('09','05', 'Churcampa'),
            array('09','06', 'Huaytará'),
            array('09','07', 'Tayacaja'),
            array('10','01', 'Huánuco'),
            array('10','02', 'Ambo'),
            array('10','03', 'Dos de Mayo'),
            array('10','04', 'Huacaybamba'),
            array('10','05', 'Huamalíes'),
            array('10','06', 'Leoncio Prado'),
            array('10','07', 'Marañón'),
            array('10','08', 'Pachitea'),
            array('10','09', 'Puerto Inca'),
            array('10','10', 'Lauricocha '),
            array('10','11', 'Yarowilca '),
            array('11','01', 'Ica '),
            array('11','02', 'Chincha '),
            array('11','03', 'Nasca '),
            array('11','04', 'Palpa '),
            array('11','05', 'Pisco '),
            array('12','01', 'Huancayo '),
            array('12','02', 'Concepción '),
            array('12','03', 'Chanchamayo '),
            array('12','04', 'Jauja '),
            array('12','05', 'Junín '),
            array('12','06', 'Satipo '),
            array('12','07', 'Tarma '),
            array('12','08', 'Yauli '),
            array('12','09', 'Chupaca '),
            array('13','01', 'Trujillo '),
            array('13','02', 'Ascope '),
            array('13','03', 'Bolívar '),
            array('13','04', 'Chepén '),
            array('13','05', 'Julcán '),
            array('13','06', 'Otuzco '),
            array('13','07', 'Pacasmayo '),
            array('13','08', 'Pataz '),
            array('13','09', 'Sánchez Carrión '),
            array('13','10', 'Santiago de Chuco '),
            array('13','11', 'Gran Chimú '),
            array('13','12', 'Virú '),
            array('14','01', 'Chiclayo '),
            array('14','02', 'Ferreñafe '),
            array('14','03', 'Lambayeque '),
            array('15','01', 'Lima '),
            array('15','02', 'Barranca '),
            array('15','03', 'Cajatambo '),
            array('15','04', 'Canta '),
            array('15','05', 'Cañete '),
            array('15','06', 'Huaral '),
            array('15','07', 'Huarochirí '),
            array('15','08', 'Huaura '),
            array('15','09', 'Oyón '),
            array('15','10', 'Yauyos '),
            array('16','01', 'Maynas '),
            array('16','02', 'Alto Amazonas '),
            array('16','03', 'Loreto '),
            array('16','04', 'Mariscal Ramón Castilla '),
            array('16','05', 'Requena '),
            array('16','06', 'Ucayali '),
            array('16','07', 'Datem del Marañón '),
            array('16','08', 'Putumayo'),
            array('17','01', 'Tambopata '),
            array('17','02', 'Manu '),
            array('17','03', 'Tahuamanu '),
            array('18','01', 'Mariscal Nieto '),
            array('18','02', 'General Sánchez Cerro '),
            array('18','03', 'Ilo '),
            array('19','01', 'Pasco '),
            array('19','02', 'Daniel Alcides Carrión '),
            array('19','03', 'Oxapampa '),
            array('20','01', 'Piura '),
            array('20','02', 'Ayabaca '),
            array('20','03', 'Huancabamba '),
            array('20','04', 'Morropón '),
            array('20','05', 'Paita '),
            array('20','06', 'Sullana '),
            array('20','07', 'Talara '),
            array('20','08', 'Sechura '),
            array('21','01', 'Puno '),
            array('21','02', 'Azángaro '),
            array('21','03', 'Carabaya '),
            array('21','04', 'Chucuito '),
            array('21','05', 'El Collao '),
            array('21','06', 'Huancané '),
            array('21','07', 'Lampa '),
            array('21','08', 'Melgar '),
            array('21','09', 'Moho '),
            array('21','10', 'San Antonio de Putina '),
            array('21','11', 'San Román '),
            array('21','12', 'Sandia '),
            array('21','13', 'Yunguyo '),
            array('22','01', 'Moyobamba '),
            array('22','02', 'Bellavista '),
            array('22','03', 'El Dorado '),
            array('22','04', 'Huallaga '),
            array('22','05', 'Lamas '),
            array('22','06', 'Mariscal Cáceres '),
            array('22','07', 'Picota '),
            array('22','08', 'Rioja '),
            array('22','09', 'San Martín '),
            array('22','10', 'Tocache '),
            array('23','01', 'Tacna '),
            array('23','02', 'Candarave '),
            array('23','03', 'Jorge Basadre '),
            array('23','04', 'Tarata '),
            array('24','01', 'Tumbes '),
            array('24','02', 'Contralmirante Villar '),
            array('24','03', 'Zarumilla '),
            array('25','01', 'Coronel Portillo '),
            array('25','02', 'Atalaya '),
            array('25','03', 'Padre Abad '),
            array('25','04', 'Purús'), 
        );
            
        
        for ($i=0; $i < count($provinces) ; $i++) { 
            DB::table('provinces')->insert([
                'region' =>$provinces[$i][0],
                'code' => $provinces[$i][1],
                'name' => $provinces[$i][2]
            ]); 
        }


    }
}
